import bb1 from '../img/b1.webp'
export const clothing = [
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Dresses', discount: '40-80% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Sarees', discount: '50-70% OFF', buttonText: 'Shop Now' },
    { image: bb1, title: 'Night suits', discount: '50-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Nightdress', discount: 'UP TO 70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Kurtas', discount: '30-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Bra', discount: 'UP TO 80% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Capris', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Ethnic Dresses', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Tops', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Tshirts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Kurta Sets', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Jackets', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Briefs', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Swimwear Cover up Bottom', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Co-Ords', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Jumpsuit', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Jeans', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Jeggings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Dress Material', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Shorts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Sweatshirts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Sweaters', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Palazzos', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Shirts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Lounge Tshirts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Trousers', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Swim Bottoms', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Swimwear', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Swim Tops', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Tights', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Track Pants', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Dupatta', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Camisoles', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Lounge Pants', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Lounge Shorts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Lehenga Choli', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Lingerie Set', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Leggings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Shawl', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Tunics', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Shapewear', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Skirts', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Stockings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '../images/shopping-bags-svgrepo-com.svg', title: 'Burqas', discount: '40-70% OFF', buttonText: 'Shop Now' },

];

export const footwear = [
    { image: '/images/wfh_casual_wear.jpg', title: 'WFH Casual Wear', discount: '40-80% OFF', buttonText: 'Shop Now' },
    { image: '/images/ethnic_wear.jpg', title: 'Ethnic Wear', discount: '50-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/western_wear.jpg', title: 'Western Wear', discount: '50-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/innerwear_sleepwear.jpg', title: 'Innerwear & Sleepwear', discount: 'UP TO 70% OFF', buttonText: 'Shop Now' },
    { image: '/images/activewear.jpg', title: 'Activewear', discount: '30-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/beauty_makeup.jpg', title: 'Beauty & Makeup', discount: 'UP TO 80% OFF', buttonText: 'Shop Now' },
    { image: '/images/kids_wear.jpg', title: 'Kids Wear', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/footwear.jpg', title: 'Footwear', discount: '40-80% OFF', buttonText: 'Shop Now' },
    { image: '/images/handbags_bags.jpg', title: 'Handbags & Bags', discount: '40-80% OFF', buttonText: 'Shop Now' },
    { image: '/images/watches.jpg', title: 'Watches', discount: 'UP TO 70% OFF', buttonText: 'Shop Now' },
    { image: '/images/jewellery.jpg', title: 'Jewellery', discount: 'UP TO 80% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
    { image: '/images/home_furnishings.jpg', title: 'Home Furnishings', discount: '40-70% OFF', buttonText: 'Shop Now' },
];
